# Generated by Django 2.2 on 2019-04-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_create_game_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='p1_discards',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='p1_draws',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='p2_discards',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='p2_draws',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
