# Generated by Django 2.2 on 2019-04-21 20:18

import dealer.models
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_game_state_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discard',
            field=django.contrib.postgres.fields.ArrayField(base_field=dealer.models.CardField(choices=[('2h', '2 of h'), ('2s', '2 of s'), ('2d', '2 of d'), ('2c', '2 of c'), ('3h', '3 of h'), ('3s', '3 of s'), ('3d', '3 of d'), ('3c', '3 of c'), ('4h', '4 of h'), ('4s', '4 of s'), ('4d', '4 of d'), ('4c', '4 of c'), ('5h', '5 of h'), ('5s', '5 of s'), ('5d', '5 of d'), ('5c', '5 of c'), ('6h', '6 of h'), ('6s', '6 of s'), ('6d', '6 of d'), ('6c', '6 of c'), ('7h', '7 of h'), ('7s', '7 of s'), ('7d', '7 of d'), ('7c', '7 of c'), ('8h', '8 of h'), ('8s', '8 of s'), ('8d', '8 of d'), ('8c', '8 of c'), ('9h', '9 of h'), ('9s', '9 of s'), ('9d', '9 of d'), ('9c', '9 of c'), ('Th', 'T of h'), ('Ts', 'T of s'), ('Td', 'T of d'), ('Tc', 'T of c'), ('Jh', 'J of h'), ('Js', 'J of s'), ('Jd', 'J of d'), ('Jc', 'J of c'), ('Qh', 'Q of h'), ('Qs', 'Q of s'), ('Qd', 'Q of d'), ('Qc', 'Q of c'), ('Kh', 'K of h'), ('Ks', 'K of s'), ('Kd', 'K of d'), ('Kc', 'K of c'), ('Ah', 'A of h'), ('As', 'A of s'), ('Ad', 'A of d'), ('Ac', 'A of c')], max_length=2), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='p1_hand',
            field=django.contrib.postgres.fields.ArrayField(base_field=dealer.models.CardField(choices=[('2h', '2 of h'), ('2s', '2 of s'), ('2d', '2 of d'), ('2c', '2 of c'), ('3h', '3 of h'), ('3s', '3 of s'), ('3d', '3 of d'), ('3c', '3 of c'), ('4h', '4 of h'), ('4s', '4 of s'), ('4d', '4 of d'), ('4c', '4 of c'), ('5h', '5 of h'), ('5s', '5 of s'), ('5d', '5 of d'), ('5c', '5 of c'), ('6h', '6 of h'), ('6s', '6 of s'), ('6d', '6 of d'), ('6c', '6 of c'), ('7h', '7 of h'), ('7s', '7 of s'), ('7d', '7 of d'), ('7c', '7 of c'), ('8h', '8 of h'), ('8s', '8 of s'), ('8d', '8 of d'), ('8c', '8 of c'), ('9h', '9 of h'), ('9s', '9 of s'), ('9d', '9 of d'), ('9c', '9 of c'), ('Th', 'T of h'), ('Ts', 'T of s'), ('Td', 'T of d'), ('Tc', 'T of c'), ('Jh', 'J of h'), ('Js', 'J of s'), ('Jd', 'J of d'), ('Jc', 'J of c'), ('Qh', 'Q of h'), ('Qs', 'Q of s'), ('Qd', 'Q of d'), ('Qc', 'Q of c'), ('Kh', 'K of h'), ('Ks', 'K of s'), ('Kd', 'K of d'), ('Kc', 'K of c'), ('Ah', 'A of h'), ('As', 'A of s'), ('Ad', 'A of d'), ('Ac', 'A of c')], max_length=2), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='p2_hand',
            field=django.contrib.postgres.fields.ArrayField(base_field=dealer.models.CardField(choices=[('2h', '2 of h'), ('2s', '2 of s'), ('2d', '2 of d'), ('2c', '2 of c'), ('3h', '3 of h'), ('3s', '3 of s'), ('3d', '3 of d'), ('3c', '3 of c'), ('4h', '4 of h'), ('4s', '4 of s'), ('4d', '4 of d'), ('4c', '4 of c'), ('5h', '5 of h'), ('5s', '5 of s'), ('5d', '5 of d'), ('5c', '5 of c'), ('6h', '6 of h'), ('6s', '6 of s'), ('6d', '6 of d'), ('6c', '6 of c'), ('7h', '7 of h'), ('7s', '7 of s'), ('7d', '7 of d'), ('7c', '7 of c'), ('8h', '8 of h'), ('8s', '8 of s'), ('8d', '8 of d'), ('8c', '8 of c'), ('9h', '9 of h'), ('9s', '9 of s'), ('9d', '9 of d'), ('9c', '9 of c'), ('Th', 'T of h'), ('Ts', 'T of s'), ('Td', 'T of d'), ('Tc', 'T of c'), ('Jh', 'J of h'), ('Js', 'J of s'), ('Jd', 'J of d'), ('Jc', 'J of c'), ('Qh', 'Q of h'), ('Qs', 'Q of s'), ('Qd', 'Q of d'), ('Qc', 'Q of c'), ('Kh', 'K of h'), ('Ks', 'K of s'), ('Kd', 'K of d'), ('Kc', 'K of c'), ('Ah', 'A of h'), ('As', 'A of s'), ('Ad', 'A of d'), ('Ac', 'A of c')], max_length=2), default=None, size=None),
            preserve_default=False,
        ),
    ]
