# Generated by Django 2.2 on 2019-04-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_game_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='p1_wins',
        ),
        migrations.RemoveField(
            model_name='game',
            name='top_card',
        ),
        migrations.AddField(
            model_name='game',
            name='p1_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='p2_points',
            field=models.IntegerField(null=True),
        ),
    ]
