# Generated by Django 2.2 on 2019-04-21 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0005_save_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_over',
            new_name='is_complete',
        ),
    ]
