# Generated by Django 2.2 on 2019-04-25 01:30

import dealer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_rename_over_to_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_draw',
            field=dealer.models.CardField(choices=[('2c', '2 of c'), ('2d', '2 of d'), ('2s', '2 of s'), ('2h', '2 of h'), ('3c', '3 of c'), ('3d', '3 of d'), ('3s', '3 of s'), ('3h', '3 of h'), ('4c', '4 of c'), ('4d', '4 of d'), ('4s', '4 of s'), ('4h', '4 of h'), ('5c', '5 of c'), ('5d', '5 of d'), ('5s', '5 of s'), ('5h', '5 of h'), ('6c', '6 of c'), ('6d', '6 of d'), ('6s', '6 of s'), ('6h', '6 of h'), ('7c', '7 of c'), ('7d', '7 of d'), ('7s', '7 of s'), ('7h', '7 of h'), ('8c', '8 of c'), ('8d', '8 of d'), ('8s', '8 of s'), ('8h', '8 of h'), ('9c', '9 of c'), ('9d', '9 of d'), ('9s', '9 of s'), ('9h', '9 of h'), ('Tc', 'T of c'), ('Td', 'T of d'), ('Ts', 'T of s'), ('Th', 'T of h'), ('Jc', 'J of c'), ('Jd', 'J of d'), ('Js', 'J of s'), ('Jh', 'J of h'), ('Qc', 'Q of c'), ('Qd', 'Q of d'), ('Qs', 'Q of s'), ('Qh', 'Q of h'), ('Kc', 'K of c'), ('Kd', 'K of d'), ('Ks', 'K of s'), ('Kh', 'K of h'), ('Ac', 'A of c'), ('Ad', 'A of d'), ('As', 'A of s'), ('Ah', 'A of h')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='turns',
            field=models.IntegerField(default=0),
        ),
    ]
