# Generated by Django 2.2 on 2019-04-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0007_game_last_draw_turns'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_draw_from_discard',
            field=models.NullBooleanField(),
        ),
    ]
