# Generated by Django 2.2 on 2019-05-03 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0008_game_last_draw_from_discard'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='p1_last_completed_turn',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 4, 1, 12, 70429)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='p2_last_completed_turn',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 4, 1, 21, 266049)),
            preserve_default=False,
        ),
    ]
