# Generated by Django 2.2 on 2019-05-03 13:56

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_default_game_series(apps, schema_editor):
    """ give all Game objects without a GameSeries the default series,
        so we have no null values in the DB
    """
    games = (apps
             .get_model('dealer', 'Game')
             .objects
             .using(schema_editor.connection.alias)
             .filter(series=None)
             )

    GameSeries = apps.get_model('dealer', 'GameSeries')
    for game in games:
        game.series = GameSeries.objects.create(
            player_1=game.player_1,
            player_2=game.player_2,
            created_at=datetime.datetime.now()
        )
        game.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealer', '0009_last_completed_turn_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('points_to_stop', models.IntegerField(default=0)),
                ('concurrent_games', models.IntegerField(default=1)),
                ('cents_per_point', models.IntegerField(default=0)),
                ('p1_points', models.IntegerField(default=0)),
                ('p2_points', models.IntegerField(default=0)),
                ('player_1',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_series',
                                   to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='second_series', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.GameSeries'),
        ),
        migrations.RunPython(code=backfill_default_game_series, reverse_code=lambda a, s: 0)
    ]
