# Generated by Django 2.2 on 2019-05-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0010_game_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_2',
        ),
        migrations.AddField(
            model_name='gameseries',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
