# Generated by Django 2.2 on 2019-05-04 21:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0011_denormalize_and_complete_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='public_hud',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
