# Generated by Django 2.2 on 2019-05-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0012_game_public_hud'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameseries',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
